// <auto-generated />
using System;
using Data.MySqlContext;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Data.MySqlContext.Migrations
{
    [DbContext(typeof(MySqlDbContext))]
    partial class MySqlDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("Data.Entities.Administation.RightEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("DescriptionResourceKey")
                        .HasColumnType("longtext");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime?>("LastSync")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("NameResourceKey")
                        .HasColumnType("longtext");

                    b.Property<Guid>("RightGuid")
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("UpdatedBy")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("RightTable");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2024, 6, 12, 12, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = "System",
                            DescriptionResourceKey = "common.FamilyAdministrationDescription",
                            IsActive = true,
                            Name = "FamilyAdministration",
                            NameResourceKey = "common.FamilyAdministration",
                            RightGuid = new Guid("551a0d01-dea8-42d8-9268-89584dd43d27"),
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UpdatedBy = ""
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2024, 6, 12, 12, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = "System",
                            DescriptionResourceKey = "common.ModuleAdministrationDescription",
                            IsActive = true,
                            Name = "ModuleAdministration",
                            NameResourceKey = "common.ModuleAdministration",
                            RightGuid = new Guid("a8711cdd-3991-4169-afd1-414fb49956a9"),
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UpdatedBy = ""
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2024, 6, 12, 12, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = "System",
                            DescriptionResourceKey = "common.SubModuleAdministrationDescription",
                            IsActive = true,
                            Name = "SubModuleAdministration",
                            NameResourceKey = "common.SubModuleAdministration",
                            RightGuid = new Guid("2b24d50e-aa2d-4201-970e-45594138e111"),
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UpdatedBy = ""
                        });
                });

            modelBuilder.Entity("Data.Entities.Administation.UserRightEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("CanCreate")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("CanDelete")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("CanEdit")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("CanView")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<bool>("Deny")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime?>("LastSync")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("RightId")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("UpdatedBy")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("RightId");

                    b.HasIndex("UserId");

                    b.ToTable("UserRightTable");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CanCreate = true,
                            CanDelete = true,
                            CanEdit = true,
                            CanView = true,
                            CreatedAt = new DateTime(2024, 6, 12, 12, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = "System",
                            Deny = false,
                            IsActive = true,
                            RightId = 1,
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UpdatedBy = "",
                            UserId = 1
                        },
                        new
                        {
                            Id = 2,
                            CanCreate = false,
                            CanDelete = false,
                            CanEdit = false,
                            CanView = true,
                            CreatedAt = new DateTime(2024, 6, 12, 12, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = "System",
                            Deny = false,
                            IsActive = true,
                            RightId = 2,
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UpdatedBy = "",
                            UserId = 1
                        },
                        new
                        {
                            Id = 3,
                            CanCreate = false,
                            CanDelete = false,
                            CanEdit = false,
                            CanView = true,
                            CreatedAt = new DateTime(2024, 6, 12, 12, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = "System",
                            Deny = false,
                            IsActive = true,
                            RightId = 3,
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UpdatedBy = "",
                            UserId = 1
                        },
                        new
                        {
                            Id = 4,
                            CanCreate = false,
                            CanDelete = false,
                            CanEdit = false,
                            CanView = false,
                            CreatedAt = new DateTime(2024, 6, 12, 12, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = "System",
                            Deny = true,
                            IsActive = true,
                            RightId = 1,
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UpdatedBy = "",
                            UserId = 2
                        },
                        new
                        {
                            Id = 5,
                            CanCreate = true,
                            CanDelete = true,
                            CanEdit = true,
                            CanView = true,
                            CreatedAt = new DateTime(2024, 6, 12, 12, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = "System",
                            Deny = false,
                            IsActive = true,
                            RightId = 2,
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UpdatedBy = "",
                            UserId = 2
                        },
                        new
                        {
                            Id = 6,
                            CanCreate = true,
                            CanDelete = true,
                            CanEdit = true,
                            CanView = true,
                            CreatedAt = new DateTime(2024, 6, 12, 12, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = "System",
                            Deny = false,
                            IsActive = true,
                            RightId = 3,
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UpdatedBy = "",
                            UserId = 2
                        });
                });

            modelBuilder.Entity("Data.Entities.FamilyEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ContactMailAddress")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("IdExternal")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime?>("LastSync")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("UpdatedBy")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("IdExternal")
                        .IsUnique();

                    b.ToTable("FamilyTable");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ContactMailAddress = "",
                            CreatedAt = new DateTime(2024, 6, 12, 12, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = "System",
                            IdExternal = "",
                            IsActive = true,
                            Name = "Default Admin Family",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UpdatedBy = ""
                        });
                });

            modelBuilder.Entity("Data.Entities.ImportFileEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<byte[]>("FileContent")
                        .IsRequired()
                        .HasColumnType("longblob");

                    b.Property<DateTime>("FileDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("FileType")
                        .HasColumnType("int");

                    b.Property<DateTime?>("LastSync")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("UpdatedBy")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("ImportFileTable");
                });

            modelBuilder.Entity("Data.Entities.Learning.ModuleEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int?>("FamilyId")
                        .HasColumnType("int");

                    b.Property<string>("IdExternal")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<DateTime?>("LastSync")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("UpdatedBy")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("FamilyId");

                    b.HasIndex("IdExternal")
                        .IsUnique();

                    b.ToTable("ModuleTable");
                });

            modelBuilder.Entity("Data.Entities.Learning.SubModuleEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int?>("FamilyId")
                        .HasColumnType("int");

                    b.Property<string>("IdExternal")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<DateTime?>("LastSync")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("ModuleId")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("UpdatedBy")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int?>("VocabularyDirection")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("FamilyId");

                    b.HasIndex("IdExternal")
                        .IsUnique();

                    b.HasIndex("ModuleId");

                    b.ToTable("SubModuleTable");
                });

            modelBuilder.Entity("Data.Entities.Learning.UnitEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("IdExternal")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("LastSync")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("SortOrder")
                        .HasColumnType("int");

                    b.Property<int>("SubModuleId")
                        .HasColumnType("int");

                    b.Property<string>("UnitContentJson")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("UnitDescription")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("UnitName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("UnitType")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("UpdatedBy")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("SubModuleId");

                    b.ToTable("UnitTable");
                });

            modelBuilder.Entity("Data.Entities.Learning.UnitResultEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<bool>("IsCompleted")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime?>("LastSync")
                        .HasColumnType("datetime(6)");

                    b.Property<double?>("Score")
                        .HasColumnType("double");

                    b.Property<int>("UnitId")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("UpdatedBy")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UnitId");

                    b.HasIndex("UserId");

                    b.ToTable("UnitResultTable");
                });

            modelBuilder.Entity("Data.Entities.Learning.UserModuleEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime?>("LastSync")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("ModuleId")
                        .HasColumnType("int");

                    b.Property<int>("ModuleType")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("UpdatedBy")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ModuleId");

                    b.HasIndex("UserId");

                    b.ToTable("UserModuleTable");
                });

            modelBuilder.Entity("Data.Entities.Learning.VocabularyEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("DanishExampleSentence")
                        .HasColumnType("longtext");

                    b.Property<string>("DanishPhoneticSpelling")
                        .HasColumnType("longtext");

                    b.Property<string>("DanishValue")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("EnglishExampleSentence")
                        .HasColumnType("longtext");

                    b.Property<string>("EnglishPhoneticSpelling")
                        .HasColumnType("longtext");

                    b.Property<string>("EnglishValue")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("FrechValue")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("FrenchExampleSentence")
                        .HasColumnType("longtext");

                    b.Property<string>("FrenchPhoneticSpelling")
                        .HasColumnType("longtext");

                    b.Property<string>("GermanExampleSentence")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("GermanPhoneticSpelling")
                        .HasColumnType("longtext");

                    b.Property<string>("GermanValue")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("IdExternal")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<DateTime?>("LastSync")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("UnitId")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("UpdatedBy")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("IdExternal")
                        .IsUnique();

                    b.HasIndex("UnitId");

                    b.ToTable("VocabularyTable");
                });

            modelBuilder.Entity("Data.Entities.Learning.VocabularyUnitEntity", b =>
                {
                    b.Property<int>("UnitId")
                        .HasColumnType("int");

                    b.Property<int>("VocabularyId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<DateTime?>("LastSync")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("UpdatedBy")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("UnitId", "VocabularyId");

                    b.HasIndex("VocabularyId");

                    b.ToTable("VocabularyUnitTable");
                });

            modelBuilder.Entity("Data.Entities.LogMessageEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("ExeptionMessage")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int?>("FamilyId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("LastSync")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("LogLevel")
                        .HasColumnType("int");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Module")
                        .HasColumnType("longtext");

                    b.Property<string>("StackTrace")
                        .HasColumnType("longtext");

                    b.Property<DateTime>("TimeStamp")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("UpdatedBy")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("FamilyId");

                    b.ToTable("LogMessageTable");
                });

            modelBuilder.Entity("Data.Entities.UserCredentialsEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("LastSync")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("RefreshToken")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Salt")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("UpdatedBy")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("CredentialsTable");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2024, 6, 12, 12, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = "System",
                            ExpiresAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PasswordHash = "UGFzc0B3b3JkMjY5NGQ0MjMtMTdiYS00ZWQ3LTg4YzctODE3ZjMzNGExMGJh",
                            RefreshToken = "",
                            Salt = "2694d423-17ba-4ed7-88c7-817f334a10ba",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UpdatedBy = ""
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2024, 6, 12, 12, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = "System",
                            ExpiresAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PasswordHash = "UGFzc0B3b3JkNjhhMzBmZTUtOGQ3MC00OTFlLTkwNjQtZmFjYzQ2MDUyMjc2",
                            RefreshToken = "",
                            Salt = "68a30fe5-8d70-491e-9064-facc46052276",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UpdatedBy = ""
                        });
                });

            modelBuilder.Entity("Data.Entities.UserEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("CredentialsId")
                        .HasColumnType("int");

                    b.Property<DateTime>("DateOfBirth")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Email")
                        .HasColumnType("longtext");

                    b.Property<int?>("FamilyId")
                        .HasColumnType("int");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("IdExternal")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("LastSync")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("SettingsId")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("UpdatedBy")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("UserRole")
                        .HasColumnType("int");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("CredentialsId")
                        .IsUnique();

                    b.HasIndex("FamilyId");

                    b.HasIndex("IdExternal")
                        .IsUnique();

                    b.HasIndex("SettingsId")
                        .IsUnique();

                    b.ToTable("UserTable");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2024, 6, 12, 12, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = "System",
                            CredentialsId = 1,
                            DateOfBirth = new DateTime(1980, 4, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "",
                            FirstName = "System",
                            IdExternal = "045a9bd4-06f9-4a55-8ab3-2dc1d692706e",
                            IsActive = true,
                            LastName = "Admin",
                            SettingsId = 1,
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UpdatedBy = "",
                            UserRole = 2,
                            Username = "System.Admin"
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2024, 6, 12, 12, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = "System",
                            CredentialsId = 2,
                            DateOfBirth = new DateTime(1980, 4, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "",
                            FamilyId = 1,
                            FirstName = "Family",
                            IdExternal = "18338480-8150-4f53-9358-d11b0f1fd9ee",
                            IsActive = true,
                            LastName = "Admin",
                            SettingsId = 2,
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UpdatedBy = "",
                            UserRole = 1,
                            Username = "Family.Admin"
                        });
                });

            modelBuilder.Entity("Data.Entities.UserSettingsEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("LastSync")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("UpdatedBy")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("SettingsTable");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2024, 6, 12, 12, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = "System",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UpdatedBy = ""
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2024, 6, 12, 12, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = "System",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UpdatedBy = ""
                        });
                });

            modelBuilder.Entity("Data.Entities.Administation.UserRightEntity", b =>
                {
                    b.HasOne("Data.Entities.Administation.RightEntity", "Right")
                        .WithMany()
                        .HasForeignKey("RightId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Data.Entities.UserEntity", "User")
                        .WithMany("UserRights")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Right");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Data.Entities.Learning.ModuleEntity", b =>
                {
                    b.HasOne("Data.Entities.FamilyEntity", "Family")
                        .WithMany()
                        .HasForeignKey("FamilyId");

                    b.Navigation("Family");
                });

            modelBuilder.Entity("Data.Entities.Learning.SubModuleEntity", b =>
                {
                    b.HasOne("Data.Entities.FamilyEntity", "Family")
                        .WithMany()
                        .HasForeignKey("FamilyId");

                    b.HasOne("Data.Entities.Learning.ModuleEntity", "Module")
                        .WithMany("SubModules")
                        .HasForeignKey("ModuleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Family");

                    b.Navigation("Module");
                });

            modelBuilder.Entity("Data.Entities.Learning.UnitEntity", b =>
                {
                    b.HasOne("Data.Entities.Learning.SubModuleEntity", "SubModule")
                        .WithMany("Units")
                        .HasForeignKey("SubModuleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SubModule");
                });

            modelBuilder.Entity("Data.Entities.Learning.UnitResultEntity", b =>
                {
                    b.HasOne("Data.Entities.Learning.UnitEntity", "Unit")
                        .WithMany()
                        .HasForeignKey("UnitId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Data.Entities.UserEntity", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Unit");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Data.Entities.Learning.UserModuleEntity", b =>
                {
                    b.HasOne("Data.Entities.Learning.ModuleEntity", "Module")
                        .WithMany()
                        .HasForeignKey("ModuleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Data.Entities.UserEntity", "User")
                        .WithMany("UserModules")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Module");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Data.Entities.Learning.VocabularyEntity", b =>
                {
                    b.HasOne("Data.Entities.Learning.UnitEntity", "Unit")
                        .WithMany()
                        .HasForeignKey("UnitId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Unit");
                });

            modelBuilder.Entity("Data.Entities.Learning.VocabularyUnitEntity", b =>
                {
                    b.HasOne("Data.Entities.Learning.UnitEntity", "Unit")
                        .WithMany()
                        .HasForeignKey("UnitId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Data.Entities.Learning.VocabularyEntity", "Vocabulary")
                        .WithMany()
                        .HasForeignKey("VocabularyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Unit");

                    b.Navigation("Vocabulary");
                });

            modelBuilder.Entity("Data.Entities.LogMessageEntity", b =>
                {
                    b.HasOne("Data.Entities.FamilyEntity", "Family")
                        .WithMany()
                        .HasForeignKey("FamilyId");

                    b.Navigation("Family");
                });

            modelBuilder.Entity("Data.Entities.UserEntity", b =>
                {
                    b.HasOne("Data.Entities.UserCredentialsEntity", "Credentials")
                        .WithOne()
                        .HasForeignKey("Data.Entities.UserEntity", "CredentialsId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Data.Entities.FamilyEntity", "Family")
                        .WithMany("Users")
                        .HasForeignKey("FamilyId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Data.Entities.UserSettingsEntity", "Settings")
                        .WithOne()
                        .HasForeignKey("Data.Entities.UserEntity", "SettingsId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Credentials");

                    b.Navigation("Family");

                    b.Navigation("Settings");
                });

            modelBuilder.Entity("Data.Entities.FamilyEntity", b =>
                {
                    b.Navigation("Users");
                });

            modelBuilder.Entity("Data.Entities.Learning.ModuleEntity", b =>
                {
                    b.Navigation("SubModules");
                });

            modelBuilder.Entity("Data.Entities.Learning.SubModuleEntity", b =>
                {
                    b.Navigation("Units");
                });

            modelBuilder.Entity("Data.Entities.UserEntity", b =>
                {
                    b.Navigation("UserModules");

                    b.Navigation("UserRights");
                });
#pragma warning restore 612, 618
        }
    }
}
