// Dummy data for IFileImportModel
import { FileImportStatusEnum } from 'src/lib/enums/FileImportStatusEnum';
import { IFileImportModel } from './interfaces/IFileImportModel';
import { FileImportTypeEnum } from 'src/lib/enums/FileImportTypeEnum';

export const dummyFileImports: IFileImportModel[] = [
  {
    fileId: 1,
    fileName: 'students_jan.csv',
    fileDate: '2025-01-10',
    fileType: FileImportTypeEnum.Family,
    status: FileImportStatusEnum.Success,
    lastUpdate: '2025-01-11',
    lastUpdateBy: 'admin',
  },
  {
    fileId: 2,
    fileName: 'teachers_feb.xlsx',
    fileDate: '2025-02-05',
    fileType: FileImportTypeEnum.Family,
    status: FileImportStatusEnum.Pending,
    lastUpdate: '2025-02-06',
    lastUpdateBy: 'user1',
  },
  {
    fileId: 3,
    fileName: 'schedule_march.csv',
    fileDate: '2025-03-12',
    fileType: FileImportTypeEnum.Family,
    status: FileImportStatusEnum.Failed,
    lastUpdate: '2025-03-13',
    lastUpdateBy: 'user2',
  },
  {
    fileId: 4,
    fileName: 'grades_apr.xlsx',
    fileDate: '2025-04-08',
    fileType: FileImportTypeEnum.Family,
    status: FileImportStatusEnum.Success,
    lastUpdate: '2025-04-09',
    lastUpdateBy: 'admin',
  },
  {
    fileId: 5,
    fileName: 'attendance_may.csv',
    fileDate: '2025-05-15',
    fileType: FileImportTypeEnum.Family,
    status: FileImportStatusEnum.Pending,
    lastUpdate: '2025-05-16',
    lastUpdateBy: 'user3',
  },
  {
    fileId: 6,
    fileName: 'students_jun.csv',
    fileDate: '2025-06-10',
    fileType: FileImportTypeEnum.Family,
    status: FileImportStatusEnum.Success,
    lastUpdate: '2025-06-11',
    lastUpdateBy: 'admin',
  },
  {
    fileId: 7,
    fileName: 'teachers_jul.xlsx',
    fileDate: '2025-07-05',
    fileType: FileImportTypeEnum.Family,
    status: FileImportStatusEnum.Failed,
    lastUpdate: '2025-07-06',
    lastUpdateBy: 'user1',
  },
  {
    fileId: 8,
    fileName: 'schedule_aug.csv',
    fileDate: '2025-08-12',
    fileType: FileImportTypeEnum.Family,
    status: FileImportStatusEnum.Pending,
    lastUpdate: '2025-08-13',
    lastUpdateBy: 'user2',
  },
  {
    fileId: 9,
    fileName: 'grades_sep.xlsx',
    fileDate: '2025-09-08',
    fileType: FileImportTypeEnum.Family,
    status: FileImportStatusEnum.Success,
    lastUpdate: '2025-09-09',
    lastUpdateBy: 'admin',
  },
  {
    fileId: 10,
    fileName: 'attendance_oct.csv',
    fileDate: '2025-10-15',
    fileType: FileImportTypeEnum.Family,
    status: FileImportStatusEnum.Failed,
    lastUpdate: '2025-10-16',
    lastUpdateBy: 'user3',
  },
  {
    fileId: 11,
    fileName: 'students_nov.csv',
    fileDate: '2025-11-10',
    fileType: FileImportTypeEnum.Family,
    status: FileImportStatusEnum.Pending,
    lastUpdate: '2025-11-11',
    lastUpdateBy: 'admin',
  },
  {
    fileId: 12,
    fileName: 'teachers_dec.xlsx',
    fileDate: '2025-12-05',
    fileType: FileImportTypeEnum.Family,
    status: FileImportStatusEnum.Success,
    lastUpdate: '2025-12-06',
    lastUpdateBy: 'user1',
  },
  {
    fileId: 13,
    fileName: 'schedule_jan.csv',
    fileDate: '2026-01-12',
    fileType: FileImportTypeEnum.Family,
    status: FileImportStatusEnum.Failed,
    lastUpdate: '2026-01-13',
    lastUpdateBy: 'user2',
  },
  {
    fileId: 14,
    fileName: 'grades_feb.xlsx',
    fileDate: '2026-02-08',
    fileType: FileImportTypeEnum.Family,
    status: FileImportStatusEnum.Pending,
    lastUpdate: '2026-02-09',
    lastUpdateBy: 'admin',
  },
  {
    fileId: 15,
    fileName: 'attendance_mar.csv',
    fileDate: '2026-03-15',
    fileType: FileImportTypeEnum.Family,
    status: FileImportStatusEnum.Success,
    lastUpdate: '2026-03-16',
    lastUpdateBy: 'user3',
  },
  {
    fileId: 16,
    fileName: 'students_apr.csv',
    fileDate: '2026-04-10',
    fileType: FileImportTypeEnum.Family,
    status: FileImportStatusEnum.Failed,
    lastUpdate: '2026-04-11',
    lastUpdateBy: 'admin',
  },
  {
    fileId: 17,
    fileName: 'teachers_may.xlsx',
    fileDate: '2026-05-05',
    fileType: FileImportTypeEnum.Family,
    status: FileImportStatusEnum.Pending,
    lastUpdate: '2026-05-06',
    lastUpdateBy: 'user1',
  },
  {
    fileId: 18,
    fileName: 'schedule_jun.csv',
    fileDate: '2026-06-12',
    fileType: FileImportTypeEnum.Family,
    status: FileImportStatusEnum.Success,
    lastUpdate: '2026-06-13',
    lastUpdateBy: 'user2',
  },
  {
    fileId: 19,
    fileName: 'grades_jul.xlsx',
    fileDate: '2026-07-08',
    fileType: FileImportTypeEnum.Family,
    status: FileImportStatusEnum.Failed,
    lastUpdate: '2026-07-09',
    lastUpdateBy: 'admin',
  },
  {
    fileId: 20,
    fileName: 'attendance_aug.csv',
    fileDate: '2026-08-15',
    fileType: FileImportTypeEnum.Family,
    status: FileImportStatusEnum.Pending,
    lastUpdate: '2026-08-16',
    lastUpdateBy: 'user3',
  },
];
